---
# yamllint disable rule:line-length

name: Actions
on:  # yamllint disable-line rule:truthy
  push:
  pull_request:
  schedule:
    - cron: "15 6 * * 1"  # 6:15 every Monday

env:
  CONTAINER_REPO: "quay.io/johnstrunk"
  CONTAINER_IMAGE: "ocs-osd-deployer"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Install prereqs
        run: |
          echo 'APT::Acquire::Retries "5";' | sudo tee /etc/apt/apt.conf.d/80-retries
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y python-pip ruby
          sudo gem install asciidoctor mdl
          sudo pip install yamllint
      - name: Run linters
        run: ./hack/pre-commit.sh --require-all

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Build container
        run: make

      - name: Export container image
        run: docker save -o /tmp/image.tar ${CONTAINER_REPO}/${CONTAINER_IMAGE}

      - name: Save container as artifact
        uses: actions/upload-artifact@v1
        with:
          name: container
          path: /tmp/image.tar

  push:
    name: Push container to registry
    needs: [build, lint]
    if: >
      (github.event_name == 'push' || github.event_name == 'schedule') &&
      (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v'))
    runs-on: ubuntu-latest

    steps:
      - name: Load container artifact
        uses: actions/download-artifact@v1
        with:
          name: container
          path: /tmp

      - name: Import container image
        run: |
          docker load -i /tmp/image.tar
          docker inspect ${CONTAINER_REPO}/${CONTAINER_IMAGE}
      - name: Login to registry
        # If the registry server is specified in the image name, we use that.
        # If the server isn't in the image name, default to docker.io
        run: |
          [[ "${CONTAINER_REPO}/${CONTAINER_IMAGE}" =~ ^([^/]+)/[^/]+/[^/]+ ]] && REGISTRY="${BASH_REMATCH[1]}" || REGISTRY="docker.io"
          echo "Attempting docker login to: ${REGISTRY}"
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin ${REGISTRY}
      - name: Push to registry (latest)
        if: >
          (github.event_name == 'push' || github.event_name == 'schedule') &&
          github.ref == 'refs/heads/master'
        run: |
          docker push "${CONTAINER_REPO}/${CONTAINER_IMAGE}"
      - name: Push to registry (version tag)
        if: >
          (github.event_name == 'push' || github.event_name == 'schedule') &&
          startsWith(github.ref, 'refs/tags/v')
        run: |
          [[ "${{ github.ref }}" =~ ^refs/tags/v([0-9]+\..*) ]] || exit 0
          TAG="${BASH_REMATCH[1]}"
          echo "Pushing to $TAG"
          docker tag "${CONTAINER_REPO}/${CONTAINER_IMAGE}" "${CONTAINER_REPO}/${CONTAINER_IMAGE}:${TAG}"
          docker push "${CONTAINER_REPO}/${CONTAINER_IMAGE}:${TAG}"
